---
version: 0.2

env:
  variables:
    VCENTER_PLATFORM: hci
  parameter-store:
    VCENTER_PASSWORD: /CodeBuild/VCENTER_PASSWORD
phases:
  pre_build:
    commands:
      - genisoimage
        -output seedconfig-amzn2/seed.iso
        -volid cidata
        -joliet
        -rock seedconfig-amzn2/user-data seedconfig-amzn2/meta-data
      - ls -al seedconfig-amzn2
  build:
    commands:
      - pwd
      - ls -lR
      - pwsh
        -File build-vmware-amzn2.ps1
            -VCenter $VCENTER_PLATFORM
            -UpdateSeedIso
            -Release
